#!/bin/bash

### BEGIN INIT INFO
# Provides:          featuretoggle
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

appName=featuretoggle
sourceDir=/var/www/featuretoggle/current/
script=app.js

pidFile=/var/www/featuretoggle/current/$appName.pid
logFile=/var/www/featuretoggle/current/logs/forever.log
outFile=/var/www/featuretoggle/current/logs/forever.out
errFile=/var/www/featuretoggle/current/logs/forever.err

daemon=/usr/bin/forever
opts="start -l $logFile -o $outFile -e $errFile --pidFile $pidFile --sourceDir $sourceDir -a -d --minUptime 2000 --spinSleepTime 100 $script"

case "$1" in
    start)
        echo "Starting $appName as user otdeploy: "
        start-stop-daemon --start --chdir $sourceDir --chuid otdeploy:otdeploy --quiet --exec $daemon --  $opts
        ;;
    stop)
        echo "Shutting down $appName: "
        start-stop-daemon --start --chuid otdeploy:otdeploy --quiet --exec $daemon --  stop ${sourceDir}app.js
        ;;
    *)
        echo "Usage:  {start|stop}"
        exit 1
        ;;
esac
exit 0